// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AraxGate.Infrastructure;

#nullable disable

namespace AraxGate.Infra.Data.Sql.Migrations
{
    [DbContext(typeof(AraxGateDbContext))]
    [Migration("20251220111909_addBaskoolOut")]
    partial class addBaskoolOut
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = "2",
                            Name = "default",
                            NormalizedName = "default"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "5731c60b-331b-4fb6-8d09-0dc241838bc1",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.AgentShippingLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AgentShippingLineCompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("ShippingLineCompanyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AgentShippingLineCompanyId");

                    b.HasIndex("ShippingLineCompanyId");

                    b.ToTable("AgentShippingLine", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.BaskoolSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaskoolMACAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BaskoolType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BaskoolSettings", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.CleaningServiceTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("CleaningServiceTariff", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.CleaningServiceTariffDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CleaningServiceTariffId")
                        .HasColumnType("int");

                    b.Property<long>("GrossWeight")
                        .HasColumnType("bigint");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double?>("Vat")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CleaningServiceTariffId");

                    b.ToTable("CleaningServiceTariffDetails", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.CommodityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommodityTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("CommodityTypes", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Consignee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ConsigneeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConsigneeNameEng")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ConsigneeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EconomicCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelNo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Consignees", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlagName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.ToTable("Countries", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ForeignDollerRate")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersianDollerRate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Currencies", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.DiscountTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FlagId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ToGrossTonage")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FlagId");

                    b.HasIndex("ModifiedById");

                    b.ToTable("DiscountTariff", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.OilTankType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TankGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TankType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OilTankTypes");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Port", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("PortEnglishName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PortSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("char(10)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Ports", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.ShippingLineCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("City")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EconomicCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsAgent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPorterage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.Property<string>("ShippingLineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ShippingLineName")
                        .IsUnique();

                    b.ToTable("ShippingLineCompany", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.TruckType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TruckTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TruckTypes", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.VatTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<double?>("TollRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("VatTariff", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Vessel", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<byte?>("ActiveCraneQty")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("BaysQuantity")
                        .HasColumnType("tinyint");

                    b.Property<string>("CallSign")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Color")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("FlagId")
                        .HasColumnType("int");

                    b.Property<int>("GrossTonage")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<int?>("VesselLength")
                        .HasColumnType("int");

                    b.Property<byte>("VesselTypeId")
                        .HasColumnType("tinyint");

                    b.Property<int?>("VesselWidth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FlagId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NationalityId");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessels", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.VesselStoppageTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("VesselStoppageTariff", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.VesselStoppageTariffDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("ExtraPrice")
                        .HasColumnType("float");

                    b.Property<int>("NormalHour")
                        .HasColumnType("int");

                    b.Property<double>("NormalPrice")
                        .HasColumnType("float");

                    b.Property<int>("VesselStoppageTarrifId")
                        .HasColumnType("int");

                    b.Property<byte>("VesselTypeId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("VesselStoppageTarrifId");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("VesselStoppageTariffDetails", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.VesselType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Voyage", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<long>("AgentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("VesselId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("OwnerId");

                    b.HasIndex("VesselId", "IsActive")
                        .IsUnique();

                    b.ToTable("Voyages", "Basic");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Billing.CleaningServiceInvoiceDetail", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<int>("ApplyCurrencyRate")
                        .HasColumnType("int");

                    b.Property<double>("ApplyPrice")
                        .HasColumnType("float");

                    b.Property<int>("CleaningServiceTariffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint");

                    b.Property<long>("DwellingHour")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InvoiceId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceR")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("PriceRVat")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("VesselStoppageId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("CleaningServiceTariffId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("VesselStoppageId")
                        .IsUnique();

                    b.ToTable("CleaningServiceInvoiceDetails", "Billing");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Billing.Invoice", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("DiscountPercent")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<bool>("IsPaied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("SumPriceD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SumPriceR")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("SumPriceRVat")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("TotalDwellingHour")
                        .HasColumnType("int");

                    b.Property<decimal>("VoyageId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("VoyageId");

                    b.ToTable("Invoices", "Billing");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Billing.VesselStoppageInvoiceDetail", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<int>("ApplyCurrencyRate")
                        .HasColumnType("int");

                    b.Property<double>("ApplyExtraPrice")
                        .HasColumnType("float");

                    b.Property<double>("ApplyNormalPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint");

                    b.Property<long>("DwellingHour")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InvoiceId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PriceD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceR")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("PriceRVat")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("VesselStoppageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("VesselStoppageTariffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("VesselStoppageId")
                        .IsUnique();

                    b.HasIndex("VesselStoppageTariffId");

                    b.ToTable("VesselStoppageInvoiceDetails", "Billing");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Operation.BaskoolOperation", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<int>("BaskoolType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BaskoolOperations", "Operation");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Operation.GateEntrance", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Baskool")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BaskoolOut")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CommodityTypeId")
                        .HasColumnType("int");

                    b.Property<long>("ConsigneeId")
                        .HasColumnType("bigint");

                    b.Property<string>("CustomPermissionNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DriverName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GateEntranceNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("GateInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GateInImageName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GateInOperatorById")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GateInOperatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("GateInWeight")
                        .HasColumnType("real");

                    b.Property<DateTime?>("GateOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GateOutImageName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GateOutOperatorById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GateOutOperatorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("GateOutWeight")
                        .HasColumnType("real");

                    b.Property<int>("OilTankTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PlateType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TruckNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TruckNoletter")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TruckTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommodityTypeId");

                    b.HasIndex("ConsigneeId");

                    b.HasIndex("GateInOperatorId");

                    b.HasIndex("GateOutOperatorId");

                    b.HasIndex("OilTankTypeId");

                    b.HasIndex("TruckTypeId");

                    b.ToTable("GateEntrances", "Operation");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Operation.VesselStoppage", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<DateTime?>("ATA")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("ATD")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ETA")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("ETD")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("EndStorm")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("NextPortId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OriginPortId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PreviousPortId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartStorm")
                        .HasColumnType("smalldatetime");

                    b.Property<decimal>("VoyageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("VoyageNoIn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("NextPortId");

                    b.HasIndex("OriginPortId");

                    b.HasIndex("PreviousPortId");

                    b.HasIndex("VoyageId");

                    b.ToTable("VesselStoppage", "Operation");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogInDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserAvatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("blank.png");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "5731c60b-331b-4fb6-8d09-0dc241838bc1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7adacc84-c4aa-49d7-bf10-be2ac8750c19",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailConfirmed = false,
                            IsActived = true,
                            LockoutEnabled = false,
                            PasswordHash = "wqBUxgeW89CN1zLLb/W2EK0+DstAEe04xfY4wqmULpo=",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1c5d42ea-86df-44b3-9574-3b06fc17d790",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.KeylessEntities.DataForDashboardChart1_Proc", b =>
                {
                    b.Property<long?>("SumPriceD")
                        .HasColumnType("bigint");

                    b.Property<long?>("SumPriceR")
                        .HasColumnType("bigint");

                    b.ToTable("DataForDashboardChart1_Proc");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.AgentShippingLine", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.ShippingLineCompany", "AgentShippingLineCompany")
                        .WithMany()
                        .HasForeignKey("AgentShippingLineCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.ShippingLineCompany", "ShippingLineCompany")
                        .WithMany("Agents")
                        .HasForeignKey("ShippingLineCompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AgentShippingLineCompany");

                    b.Navigation("ShippingLineCompany");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.CleaningServiceTariff", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.CleaningServiceTariffDetails", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.CleaningServiceTariff", "CleaningServiceTariff")
                        .WithMany("CleaningServiceTariffDetails")
                        .HasForeignKey("CleaningServiceTariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CleaningServiceTariff");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Consignee", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Currency", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.DiscountTariff", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Country", "Flag")
                        .WithMany()
                        .HasForeignKey("FlagId");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Flag");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Port", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Country", "Country")
                        .WithMany("Ports")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.ShippingLineCompany", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.VatTariff", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Vessel", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Country", "Flag")
                        .WithMany("Flags")
                        .HasForeignKey("FlagId");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Country", "Nationality")
                        .WithMany("Nationalities")
                        .HasForeignKey("NationalityId");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.VesselType", "Type")
                        .WithMany("Vessels")
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Flag");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Nationality");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.VesselStoppageTariff", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.VesselStoppageTariffDetails", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.VesselStoppageTariff", "VesselStoppageTarriff")
                        .WithMany("VesselStoppageTariffDetails")
                        .HasForeignKey("VesselStoppageTarrifId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.VesselType", "VesselType")
                        .WithMany("VesselStoppageTariffDetails")
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VesselStoppageTarriff");

                    b.Navigation("VesselType");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Voyage", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.ShippingLineCompany", "Agent")
                        .WithMany("AgentVoyages")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.ShippingLineCompany", "Owner")
                        .WithMany("OwnerVoyages")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Vessel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Owner");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Billing.CleaningServiceInvoiceDetail", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.CleaningServiceTariff", "CleaningServiceTariff")
                        .WithMany("CleaningServiceInvoiceDetail")
                        .HasForeignKey("CleaningServiceTariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Billing.Invoice", "Invoice")
                        .WithMany("CleaningServiceInvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Operation.VesselStoppage", "VesselStoppage")
                        .WithOne("CleaningServiceInvoiceDetail")
                        .HasForeignKey("SinaOTOS.Core.Domain.Entities.Billing.CleaningServiceInvoiceDetail", "VesselStoppageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CleaningServiceTariff");

                    b.Navigation("CreatedBy");

                    b.Navigation("Currency");

                    b.Navigation("Invoice");

                    b.Navigation("ModifiedBy");

                    b.Navigation("VesselStoppage");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Billing.Invoice", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Voyage", "Voyage")
                        .WithMany()
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Billing.VesselStoppageInvoiceDetail", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Billing.Invoice", "Invoice")
                        .WithMany("VesselStoppageInvoiceDetails")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Operation.VesselStoppage", "VesselStoppage")
                        .WithOne("VesselStoppageInvoiceDetail")
                        .HasForeignKey("SinaOTOS.Core.Domain.Entities.Billing.VesselStoppageInvoiceDetail", "VesselStoppageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.VesselStoppageTariff", "VesselStoppageTariff")
                        .WithMany("VesselStoppageInvoiceDetail")
                        .HasForeignKey("VesselStoppageTariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Currency");

                    b.Navigation("Invoice");

                    b.Navigation("ModifiedBy");

                    b.Navigation("VesselStoppage");

                    b.Navigation("VesselStoppageTariff");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Operation.GateEntrance", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.CommodityType", "CommodityType")
                        .WithMany("GateEntrances")
                        .HasForeignKey("CommodityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Consignee", "Consignee")
                        .WithMany("GateEntrances")
                        .HasForeignKey("ConsigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "GateInOperator")
                        .WithMany()
                        .HasForeignKey("GateInOperatorId");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "GateOutOperator")
                        .WithMany()
                        .HasForeignKey("GateOutOperatorId");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.OilTankType", "OilTankType")
                        .WithMany("GateEntrances")
                        .HasForeignKey("OilTankTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.TruckType", "TruckType")
                        .WithMany("GateEntrances")
                        .HasForeignKey("TruckTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommodityType");

                    b.Navigation("Consignee");

                    b.Navigation("GateInOperator");

                    b.Navigation("GateOutOperator");

                    b.Navigation("OilTankType");

                    b.Navigation("TruckType");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Operation.VesselStoppage", b =>
                {
                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Port", "NextPort")
                        .WithMany()
                        .HasForeignKey("NextPortId");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Port", "OriginPort")
                        .WithMany()
                        .HasForeignKey("OriginPortId");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Port", "PreviousPort")
                        .WithMany()
                        .HasForeignKey("PreviousPortId");

                    b.HasOne("SinaOTOS.Core.Domain.Entities.Basic.Voyage", "Voyage")
                        .WithMany("VesselStoppages")
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("NextPort");

                    b.Navigation("OriginPort");

                    b.Navigation("PreviousPort");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.CleaningServiceTariff", b =>
                {
                    b.Navigation("CleaningServiceInvoiceDetail");

                    b.Navigation("CleaningServiceTariffDetails");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.CommodityType", b =>
                {
                    b.Navigation("GateEntrances");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Consignee", b =>
                {
                    b.Navigation("GateEntrances");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Country", b =>
                {
                    b.Navigation("Flags");

                    b.Navigation("Nationalities");

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.OilTankType", b =>
                {
                    b.Navigation("GateEntrances");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.ShippingLineCompany", b =>
                {
                    b.Navigation("AgentVoyages");

                    b.Navigation("Agents");

                    b.Navigation("OwnerVoyages");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.TruckType", b =>
                {
                    b.Navigation("GateEntrances");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.VesselStoppageTariff", b =>
                {
                    b.Navigation("VesselStoppageInvoiceDetail");

                    b.Navigation("VesselStoppageTariffDetails");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.VesselType", b =>
                {
                    b.Navigation("VesselStoppageTariffDetails");

                    b.Navigation("Vessels");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Basic.Voyage", b =>
                {
                    b.Navigation("VesselStoppages");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Billing.Invoice", b =>
                {
                    b.Navigation("CleaningServiceInvoiceDetails");

                    b.Navigation("VesselStoppageInvoiceDetails");
                });

            modelBuilder.Entity("SinaOTOS.Core.Domain.Entities.Operation.VesselStoppage", b =>
                {
                    b.Navigation("CleaningServiceInvoiceDetail");

                    b.Navigation("VesselStoppageInvoiceDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
